---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
  - name: Get software for apt repository management
    apt: name={{ item }} state=present
    with_items:
      - python-apt
      - python-pycurl
