---
# All roles are installed from Ansible Galaxy
- src: manala.zsh
- src: gantsign.oh-my-zsh
- src: geerlingguy.nodejs
- src: DavidWittman.redis
- src: ANXS.postgresql
- src: greendayonfire.mongodb
- src: geerlingguy.nginx
- src: rvm_io.ruby
