---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: manala.zsh
    - role: server_configuration

  tasks:
    - name: Install zsh for deploy user
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ deploy_user_name }}"

    - name: Install nodejs for deploy user
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: geerlingguy.nodejs
      vars:
        users:
          - username: "{{ deploy_user_name }}"

    - name: Install required software
      remote_user: "{{ deploy_user_name }}"
      apt: name={{ item }}
      with_items:
        - curl
        - libpq-dev
        - htop

    - name: Install redis
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: DavidWittman.redis
      vars:
        - redis_bind: 127.0.0.1
      when: (redis_enabled is defined) and redis_enabled

    - name: Install PostgreSQL
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: ANXS.postgresql
      vars:
          postgresql_version: 9.6
          postgresql_encoding: 'UTF-8'
          postgresql_locale: 'en_US.UTF-8'
          postgresql_admin_user: 'postgres'
          postgresql_default_auth_method: 'trust'
          postgresql_service_enabled: true
      when: "(database is defined) and database == 'postgresql'"

    - name: Install mongodb
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: greendayonfire.mongodb
      vars:
          mongodb_version: "3.4"
          mongodb_manage_service: true
      when: "(database is defined) and database == 'mongodb'"

    - name: NGINX | Configutation
      import_role:
          name: nginx_configuration
