---
- hosts: all
  become: yes
  become_method: sudo
  roles:
    - role: manala.zsh
    - role: server_configuration

  tasks:
    - name: Install zsh for deploy user
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: gantsign.oh-my-zsh
      vars:
        users:
          - username: "{{ deploy_user_name }}"

    - name: Install nodejs for deploy user
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: geerlingguy.nodejs
      vars:
        users:
          - username: "{{ deploy_user_name }}"

    - name: Install required software
      remote_user: "{{ deploy_user_name }}"
      apt: name={{ item }}
      with_items:
        - curl
        - libpq-dev
        - htop

    - name: Install redis
      remote_user: "{{ deploy_user_name }}"
      import_role:
          name: DavidWittman.redis
      vars:
        - redis_bind: 127.0.0.1
      when: (redis_enabled is defined) and redis_enabled
