---
- name: Ruby | Install GNUPG
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - gnupg2

- name: Ruby | ensure that GPG key for RVM is installed
  command: gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
  args:
    creates: /root/.gnupg/secring.gpg

- name: ensure that RVM is installed
  shell: curl -L get.rvm.io | bash -s stable
  args:
    creates: /usr/local/rvm

- name: ensure that ruby is installed
  command: "rvm install {{ ruby_version }}"
  args:
    creates: "/usr/local/rvm/gems/ruby-{{ ruby_version }}"

- name: set default version of ruby with rvm
  command: "rvm alias create default ruby-{{ ruby_version }}"
  args:
    creates: /usr/local/rvm/config/alias
